linguispark/Controllers/cevirmenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using linguispark.Models.entity;
namespace linguispark.Controllers
{
    public class cevirmenController : Controller
    {
        linguisparkEntities1 db = new linguisparkEntities1();
        // GET: cevrimenEkle
        public ActionResult Index()
        {
            var degerler = db.tblCevirmen.Where(i => i.durum == true).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult cevirmenEKle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult cevirmenEKle(tblCevirmen p)
        {
            db.tblCevirmen.Add(p);
            p.durum = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult cevirmenSil(int id)
        {
            var cevirmen = db.tblCevirmen.Find(id);
            cevirmen.durum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult cevirmenGuncellemeSayfasi(int id)
        {
            var cevirmen = db.tblCevirmen.Find(id);
            return View("cevirmenGuncellemeSayfasi", cevirmen);
        }
        [HttpPost]
        public ActionResult cevirmenGuncelle(tblCevirmen p)
        {
            var cevirmen = db.tblCevirmen.Find(p.id);
            cevirmen.cevirmenAdi = p.cevirmenAdi;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

linguispark/Views/cevirmen/Index.cshtml
@using linguispark.Models.entity
@model List<tblCevirmen>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>Çevirmen Listesi</h2>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Çevirmen Adı</th>
        <th>Sil</th>
        <th>Güncele</th>
    </tr>

    <tbody>
        @foreach (var i in Model)
        {
            <tr>
                <td>@i.id</td>
                <td>@i.cevirmenAdi</td>
                <td><a href="/cevirmen/cevirmenSil/@i.id" class="btn btn-warning">Sil</a></td>
                <td><a href="/cevirmen/cevirmenGuncellemeSayfasi/@i.id" class="btn btn-success">Güncelle</a></td>
            </tr>
        }
    </tbody>

</table>
<a href="/cevirmen/cevirmenEKle" class="btn btn-primary">Çevirmen Ekle</a>

linguispark/Views/cevirmen/cevirmenEKle.cshtml
@model linguispark.Models.entity.tblCevirmen
@{
    ViewBag.Title = "cevirmenEKle";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>cevirmenEKle</h2>

@using (Html.BeginForm("cevirmenEkle", "cevirmen", FormMethod.Post))
{
    <div class="form-group">
        <label>CevirmenAdi</label>
        @Html.TextBoxFor(i => i.cevirmenAdi, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(i => i.id)
    <button class="btn btn-primary">Ekle</button>
}

linguispark/Views/cevirmen/cevirmenGuncellemeSayfasi.cshtml
@model linguispark.Models.entity.tblCevirmen
@{
    ViewBag.Title = "cevirmenGuncellemeSayfasi";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>Çevirmen Güncelleme Sayfası</h2>

@using (Html.BeginForm("cevirmenGuncelle", "cevirmen", FormMethod.Post))
{
    <div class="form-group">
        <label>CevirmenAdi</label>
        @Html.TextBoxFor(i => i.cevirmenAdi, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(i => i.id)
    <button class="btn btn-primary">Güncelle</button>
}