linguispark/Controllers/satinAlimFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using linguispark.Models.entity;
using linguispark.Controllers;
using System.Net.Mail;
using linguispark.Helpers;
namespace linguispark.Controllers
{
    public class satinAlimFormController : Controller
    {
        linguisparkEntities1 db = new linguisparkEntities1();
        
        //// GET: satinAlimForm
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult satinAlimSayfasiA(int id)
        {
            List<SelectListItem> cevirmenList = (from x in db.tblCevirmen.ToList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.cevirmenAdi,
                                                     Value = x.id.ToString(),
                                                     Selected = (x.id == id)
                                                 }).ToList();
            var satis = db.tblSatis.Find(id);
            ViewBag.cevirmenAdi = cevirmenList;
            if (satis != null && !cevirmenList.Any(x => x.Value == satis.cevirmen.ToString()))
            {
                var defaultSelected = cevirmenList.FirstOrDefault();
                if (defaultSelected != null)
                    defaultSelected.Selected = true;
            }


            return View();
        }

        [HttpGet]
        public ActionResult satinAlim()
        {
            return View();
        }
        [HttpPost]
        public ActionResult satinAlim(tblSatis p)
        {
            // var cevir = db.tblCevirmen.Where(x => x.id==p.cevirmen).FirstOrDefault();
            //if (p.cevirmen == null)
            //{
            //    var defaultSelected = db.tblSatis.Find(p.id)?.cevirmen;
            //    p.cevirmen = defaultSelected;
            //}

            if (p.cevirmen == null)
            {
                p.cevirmen = null;
            }
            else
            {
                // Geçerli bir çevirmen seçilmişse, sadece o çevirmenin ID'sini atayın
                p.cevirmen = db.tblSatis.Find(p.id)?.cevirmen;
            }
            db.tblSatis.Add(p);
            db.SaveChanges();
     

            string toAddress = p.Mail.ToString(); // Alıcı e-posta adresi
            string subject = "Satın Alma Onayı"; // E-posta konusu
            string body = "Satın alma işlemi başarıyla gerçekleştirildi."; // E-posta içeriği

            EmailHelper.SendEmail(toAddress, subject, body);

            return RedirectToAction("Index", "satinAlindiBilgiSayfasi");

        }
    }
}

linguispark/Views/satinAlimForm/satinAlimSayfasiA.cshtml
@model linguispark.Models.entity.tblSatis
@{
    ViewBag.Title = "satinAlimSayfasiA";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>satinAlimSayfasiA</h2>

@using (Html.BeginForm("satinAlim", "satinAlimForm", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>Müşteri Ad Soyad</label>
                @Html.TextBoxFor(x => x.musteriAdSoyad, new { @class = "form-control" })
            </div>
            <br />
            <div class="form-group">
                <label>Çevirmen: </label>
                @*@Html.DropDownListFor(x => x.tblCevirmen.id, (List<SelectListItem>)ViewBag.cevirmenAdi, new { @class = "form-control" })*@
                @Html.DropDownListFor(x => x.cevirmen, (List<SelectListItem>)ViewBag.cevirmenAdi, "Seçiniz", new { @class = "form-control" })
            </div>
            <br />
            <div class="form-group">
                <label>Fiyat</label>
                @Html.TextBoxFor(x => x.fiyat, new { @class = "form-control" })
            </div>
            <br />
            <div class="form-group">
                <label>Tarih</label>
                @Html.TextBoxFor(x => x.tarih, new { @class = "form-control" })
            </div>
        </div>
        <br />
        <div class="col-md-6">
            <div class="form-group">
                <label>Mail</label>
                @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
            </div>
            <br />
            <div class="form-group">
                <label>Telefon</label>
                @Html.TextBoxFor(x => x.telefon, new { @class = "form-control" })
            </div>
            <br />
            <div class="form-group">
                <label>Adres</label>
                @Html.TextBoxFor(x => x.adres, new { @class = "form-control" })
            </div>
            <br />
        </div>
    </div>
    <br />
    @Html.HiddenFor(x => x.id)
    <button class="btn btn-primary">Satın Al</button>

}