linguispark/Controllers/CevirmenKartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using linguispark.Models.entity;
namespace linguispark.Controllers
{
    public class CevirmenKartController : Controller
    {
        linguisparkEntities1 db = new linguisparkEntities1();
        // GET: CevirmenKart
        public ActionResult Index()
        {
            var degerler = db.tblKart.Where(i=>i.kartDurum==true).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult kartEkle()
        {
            List<SelectListItem> kart = (from x in db.tblCevirmen.ToList()
                                         where(x.durum==true)
                                         select new SelectListItem
                                         {
                                             Text = x.cevirmenAdi,
                                             Value = x.id.ToString()
                                         }).ToList();
            ViewBag.kartlar = kart;
            return View();
        }
        [HttpPost]
        public ActionResult kartEkle(tblKart p)
        {
            var kart = db.tblKart.Where(x => x.id == p.kartBaslikCevirmenAdi).FirstOrDefault();
            db.tblKart.Add(p);
            p.kartDurum = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult kartSil(int id)
        {
            var kart = db.tblKart.Find(id);
            kart.kartDurum= false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult kartGuncellemeSayfasi(int id)
        {
            List<SelectListItem> kart = (from x in db.tblCevirmen.ToList()
                                         where (x.durum == true)
                                         select new SelectListItem
                                         {
                                             Text = x.cevirmenAdi,
                                             Value = x.id.ToString()
                                         }).ToList();
            ViewBag.kartlar = kart;
            var karts = db.tblKart.Find(id);
            return View("kartGuncellemeSayfasi", karts);
        }
        [HttpPost]
        public ActionResult kartGuncelle(tblKart p)
        {
            var kart = db.tblKart.Find(p.id);
            kart.kartBaslikCevirmenAdi = p.kartBaslikCevirmenAdi;
            kart.kartAciklama = p.kartAciklama;
            kart.kartFotograf = p.kartFotograf;
            var karts = db.tblCevirmen.Where(x => x.id == p.id).FirstOrDefault();
            kart.kartBaslikCevirmenAdi = karts.id;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

linguispark/Views/CevirmenKart/Index.cshtml
@using linguispark.Models.entity
@model List<tblKart>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>Index</h2>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Kart Başlık (Çevirmen Adı)</th>
        <th>Kart Açıklama (Çeviri Ücret)</th>
        <th>Fotoğraf</th>
        <th>Durum</th>
        <th>Sil</th>
        <th>Güncele</th>
    </tr>

    <tbody>
        @foreach (var i in Model)
        {
            <tr>
                <td>@i.id</td>
                <td>@i.tblCevirmen.cevirmenAdi</td>
                <td>@i.kartAciklama</td>
                <td>@i.kartFotograf</td>
                <td>@i.kartDurum</td>
                <td><a href="/CevirmenKart/kartSil/@i.id" class="btn btn-warning">Sil</a></td>
                <td><a href="/CevirmenKart/kartGuncellemeSayfasi/@i.id" class="btn btn-success">Güncelle</a></td>
            </tr>
        }
    </tbody>

</table>
<a href="/CevirmenKart/kartEkle" class="btn btn-primary">Kart Ekle</a>

linguispark/Views/CevirmenKart/kartEkle.cshtml
@model linguispark.Models.entity.tblKart
@{
    ViewBag.Title = "kartEkle";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>Kart Ekle</h2>

@using (Html.BeginForm("kartEkle", "CevirmenKart", FormMethod.Post))
{
<div class="form-group">
    <label>Kart Başlık (Cevirmen Adı)</label>
    @Html.DropDownListFor(x => x.kartBaslikCevirmenAdi, (List<SelectListItem>)ViewBag.kartlar, new { @class = "form-control" })
</div>
    <div class="form-group">
        <label>Kart Açıklama (Ücret)</label>
        @Html.TextBoxFor(i => i.kartAciklama, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Kart Fotoğraf Link</label>
        @Html.TextBoxFor(i => i.kartFotograf, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(i => i.id)
    <button class="btn btn-primary">Ekle</button>
}

linguispark/Views/CevirmenKart/kartGuncellemeSayfasi.cshtml
@model linguispark.Models.entity.tblKart
@{
    ViewBag.Title = "kartGuncellemeSayfasi";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>Kart Güncelleme Sayfası</h2>

@using (Html.BeginForm("kartGuncelle", "CevirmenKart", FormMethod.Post))
{
<div class="form-group">
    <label>Kart Başlık (Cevirmen Adı)</label>
    @Html.DropDownListFor(x => x.tblCevirmen.id, (List<SelectListItem>)ViewBag.kartlar, new { @class = "form-control" })
</div>
    <div class="form-group">
        <label>Kart Açıklama (Ücret)</label>
        @Html.TextBoxFor(i => i.kartAciklama, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Kart Fotoğraf Link</label>
        @Html.TextBoxFor(i => i.kartFotograf, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(i => i.id)
    <button class="btn btn-primary">Güncelle</button>
}