linguispark/Controllers/projeHakkindaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using linguispark.Models.entity;
namespace linguispark.Controllers
{
    public class projeHakkindaController : Controller
    {
        // GET: projeHakkinda
        linguisparkEntities1 db = new linguisparkEntities1();
        public ActionResult Index()
        {
            var degerler = db.tblProjeHakkinda.ToList();
            return View(degerler);

        }

        public ActionResult Index1()
        {
            var degerler = db.tblProjeHakkinda.ToList();
            return View(degerler);
        }
        public ActionResult projeHakkindaSil(int id)
        {
            var deger = db.tblProjeHakkinda.Find(id);
            db.tblProjeHakkinda.Remove(deger);
            db.SaveChanges();
            return RedirectToAction("Index1");
        }
        public ActionResult projeHakkindaGuncellemeSayfasi(int id)
        {
            var degerler = db.tblProjeHakkinda.Find(id);
            return View("projeHakkindaGuncellemeSayfasi", degerler);
        }
        [HttpPost]
        public ActionResult projeHakkindaGuncelle(tblProjeHakkinda p)
        {
            var degerler = db.tblProjeHakkinda.Find(p.id);
            degerler.fotograf = p.fotograf;
            degerler.projeHakkinda = p.projeHakkinda;
            db.SaveChanges();
            return RedirectToAction("Index1");
        }
    }
}

linguispark/Views/projeHakkinda/Index.cshtml
@using linguispark.Models.entity
@model List<tblProjeHakkinda>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Proje Hakkında</h2>

<section>
    <section>
        @foreach (var i in Model)
        {
            <div class="row">
                <div class="col-md-4">
                    <img class="img-fluid" src="~/adminTema/4580151-html-programming-code-blue-simplicity.jpg" />
                </div>
                <div class="col-md-8">
                    <p style="white-space: pre-wrap; font-size: 1.5rem;" class="text-wrap">@i.projeHakkinda</p>
                </div>
            </div>
            <br />
        }
    </section>

</section>

linguispark/Views/projeHakkinda/Index1.cshtml
@using linguispark.Models.entity
@model List<tblProjeHakkinda>
@{
    ViewBag.Title = "Index1";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>Proje Hakkında Listesi</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Proje Hakkında</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>

    <tbody>
        @foreach(var i in Model)
            {
        <tr>
            <td>@i.id</td>
            <td style="max-width: 0; word-wrap: break-word;">@i.projeHakkinda</td>
            <td><a <a href="/projeHakkinda/projeHakkindaSil/@i.id" class="btn btn-warning">Sil</a></td>
            <td><a href="/projeHakkinda/projeHakkindaGuncellemeSayfasi/@i.id" class="btn btn-success">Güncelle</a></td>
        </tr>
            }
    </tbody>
</table>

linguispark/Views/projeHakkinda/projeHakkindaGuncellemeSayfasi.cshtml
@model linguispark.Models.entity.tblProjeHakkinda
@{
    ViewBag.Title = "projeHakkindaGuncellemeSayfasi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Proje Hakkında Güncelleme Sayfası</h2>

@using (Html.BeginForm("projeHakkindaGuncelle", "projeHakkinda", FormMethod.Post))
{
    <br />
    <div class="form-group">
        <label>Proje Hakkında</label>
        <br />
        @Html.TextAreaFor(i => i.projeHakkinda, new { @class = "form-control", rows = "6" })
    </div>
    <br />
    @Html.HiddenFor(i => i.id)
    <br />
    <button class="btn btn-primary">Güncelle</button>
}